// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80Mr4yBjYINEkPyiUU603f1swm_CwdAY',
    appId: '1:959193612306:web:485a1388122fc7eece18cb',
    messagingSenderId: '959193612306',
    projectId: 'chattyapp-29037',
    authDomain: 'chattyapp-29037.firebaseapp.com',
    storageBucket: 'chattyapp-29037.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJkAxATqjEWEOube3HfEo6XGzHjRAYw8',
    appId: '1:959193612306:android:b3edf7a9c1788167ce18cb',
    messagingSenderId: '959193612306',
    projectId: 'chattyapp-29037',
    storageBucket: 'chattyapp-29037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQKKor4IyYMuE8CaAt8uXEw1xvWMFACec',
    appId: '1:959193612306:ios:e2df4d0fade92763ce18cb',
    messagingSenderId: '959193612306',
    projectId: 'chattyapp-29037',
    storageBucket: 'chattyapp-29037.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQKKor4IyYMuE8CaAt8uXEw1xvWMFACec',
    appId: '1:959193612306:ios:e2df4d0fade92763ce18cb',
    messagingSenderId: '959193612306',
    projectId: 'chattyapp-29037',
    storageBucket: 'chattyapp-29037.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA80Mr4yBjYINEkPyiUU603f1swm_CwdAY',
    appId: '1:959193612306:web:e485e431d976d4edce18cb',
    messagingSenderId: '959193612306',
    projectId: 'chattyapp-29037',
    authDomain: 'chattyapp-29037.firebaseapp.com',
    storageBucket: 'chattyapp-29037.appspot.com',
  );
}
